---
- name: Fix Docker Installation
  hosts: all
  become: yes
  tasks:
    # Clean up existing Docker artifacts
    - name: Remove existing Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        state: absent
      ignore_errors: yes

    - name: Remove Docker repository file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      ignore_errors: yes

    # Install prerequisites
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    # Configure Docker repository properly
    - name: Create trusted key directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key (new method)
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker.list
        state: present

    # Force full package cache update
    - name: Clean apt cache
      ansible.builtin.command:
        cmd: apt-get clean

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    # Install Docker components
    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        force: yes

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes