---
- name: Install MongoDB
  hosts: all
  become: yes
  tasks:
    # Clean up conflicting repositories
    - name: Remove NodeSource repository
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/nodesource.list
        state: absent
      ignore_errors: yes

    - name: Remove Docker repository
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      ignore_errors: yes

    # Install MongoDB
    - name: Install prerequisites
      ansible.builtin.apt:
        name: 
          - gnupg
          - curl
        state: present
        update_cache: yes

    - name: Import MongoDB GPG key
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        state: present

    - name: Add MongoDB repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu {{ (ansible_distribution_release == 'noble') | ternary('jammy', ansible_distribution_release) }}/mongodb-org/7.0 multiverse"
        filename: mongodb-org-7.0.list
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install MongoDB packages
      ansible.builtin.apt:
        name:
          - mongodb-org
          - mongodb-org-database-tools-extra
        state: present

    - name: Start MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes