---
- name: Install Node.js
  hosts: all
  become: yes
  vars:
    node_version: "22.x"  # Can be 20.x, 21.x, 22.x
  tasks:
    - name: Remove existing NodeSource repository
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/nodesource.list
        state: absent
      ignore_errors: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add NodeSource GPG key
      ansible.builtin.apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeSource repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release | default('jammy') }} main"
        filename: nodesource.list
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Node.js and npm
      ansible.builtin.apt:
        name:
          - nodejs
        state: present

    - name: Install build essentials (optional)
      ansible.builtin.apt:
        name:
          - build-essential
        state: present

    - name: Verify Node.js installation
      ansible.builtin.command:
        cmd: node --version
      register: node_version_check
      changed_when: false

    - name: Show Node.js version
      ansible.builtin.debug:
        msg: "Node.js {{ node_version_check.stdout }} installed successfully"