name: CI for ansible assisntant

run-name: ${{ github.actor }} is running workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install flake8 pytest

      - name: Create SSH Config File
        run: |
          mkdir -p ~/.ssh
          echo "Host Host_x" > ~/.ssh/config
          echo "  HostName x" >> ~/.ssh/config
          echo "  User x_user" >> ~/.ssh/config
          echo "  #Port qwert" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  PasswordAuthentication no" >> ~/.ssh/config
          echo "  IdentityFile ~/path/to/private_key" >> ~/.ssh/config
          echo "  IdentitiesOnly yes" >> ~/.ssh/config
          echo "  LogLevel FATAL" >> ~/.ssh/config
          echo "  PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config
          echo "  HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
          cat ~/.ssh/config

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Building image and running
        run: |
          docker build -t ansible_assistant:latest .
          docker compose up -d

      - name: Lint
        run:
          echo "linting code"
          docker exec -it ansible_assistant bash
          flake8 ./src


