name: CI for ansible assistant

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint code
        run: flake8 ./src

      - name: Create mock SSH config
        run: |
          mkdir -p src/mock_ssh
          echo "Host *" > src/mock_ssh/config
          echo "    StrictHostKeyChecking no" >> src/mock_ssh/config
        env:
          SSH_CONFIG_PATH: "./src/mock_ssh/config"

      - name: Run unit tests
        env:
          SSH_CONFIG_PATH: "./src/mock_ssh/config"
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          pytest ./tests -v
